name: invi-app
services:
  postgres:
    image: postgres:16.1
    container_name: invi-app
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
